### PR TITLE
Update Sphinx theme

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary
Updates to new Ecosystem theme.

For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232

### CODE REVIEW

**Comment by mrossinek** [comment]
How does this relate to #40?

**Comment by frankharkins** [comment]
@mrossinek: This project is being taken over by @arnaucasau, I'll close the other PR

**Review by frankharkins — COMMENTED** [review]
Just tested locally and it works well for me. Thanks @arnaucasau!

**Comment by mrossinek** [comment]
Since this takes over from #40 but that was still a draft, should this also be considered a draft or is this actually good to go? I do not know if you have any timeline in mind/want to sync this with some other documentation aspects or if this is decoupled and can be merged any time.

**Comment by frankharkins** [comment]
Sorry for the poor communication. Yes this PR is ready to be reviewed and can be merged at any time.

**Review by mrossinek — APPROVED** [review]
Thanks! :+1: 

Docs will be republished with the next release (once #43 gets unblocked and subsequently merged).

**Pull request merged**
